### PR TITLE
Allow ds.NewTransaction() to return an error

### PR DESCRIPTION
**Pull request by raulk**

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

**Review by bigs — APPROVED** [review]

**Review by magik6k — APPROVED** [review]

**Comment by Kubuxu** [comment]
This is API change, so in theory, it should be go-datastore 4.0.0. From another side, it is just a change in `TxDatastore`.

**Comment by raulk** [comment]
@Kubuxu had the very same dilemma. Pragmatically it should be a major bump, but I don't want to pollute that namespace for such a narrowly-scoped change. All downstream DS are being updated in lockstep. Any gripes with keeping it a minor?

**Comment by raulk** [comment]
https://github.com/ipfs/go-ds-badger/pull/36
https://github.com/ipfs/go-ds-leveldb/pull/17

**Comment by Kubuxu** [comment]
SGWM

**Comment by bigs** [comment]
feel free to merge these all!

**Pull request merged**
