### PR TITLE
allow put to try again if it fails due to too many open files

### PR DESCRIPTION
**Pull request by whyrusleeping**
A small workaround to try and mitigate the 'too many open file descriptors' issues we are seeing.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
One issue i have with this is that we dont get to see when these temporary failures occur. It might be okay, but i'm paranoid.

**Comment by jbenet** [comment]
Log them?

(we should make the `util.Logger` thing its own package or something, so go-datastore and go-commands can import it)

**Comment by whyrusleeping** [comment]
> (we should make the util.Logger thing its own package or something, so go-datastore and go-commands can import it)

I'll do that, its a good idea.

**Comment by jbenet** [comment]
@whyrusleeping squash

**Comment by whyrusleeping** [comment]
squashed

**Pull request merged**
