### PR TITLE
Wire flatfs sync argument into Datastore creation

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by whyrusleeping** [comment]
LGTM, sorry about that.

**Comment by jbenet** [comment]
Could we test this somehow?

Wow I failed at CR too

**Comment by rht** [comment]
- `rm -r ~/.ipfs && ipfs init -f && ipfs add -q -r Godeps` 1:16.15
- `rm -r ~/.ipfs && ipfs init -f && ipfs config Datastore.NoSync true && ipfs add -q -r Godeps` 1.017

**Comment by jbenet** [comment]
i mean in this repo

**Pull request merged**
