### PR TITLE
add context parameter to datastore interface

### PR DESCRIPTION
**Pull request by lanzafame**
This PR adds context.Context as the first parameter to the datastore interface. This allows for tracing and metrics tools to pass through the datastore interface, providing a better understanding of performance.

To allow for backwards compatibility, I would recommend that this be part of go-datastore/v2 allowing downstream packages to upgrade at their leisure.

### CODE REVIEW

**Comment by lanzafame** [comment]
@Stebalien thoughts? I can't request reviewers anymore it seems...

**Comment by Stebalien** [comment]
Is this just a rebase of https://github.com/ipfs/go-datastore/pull/161/files?

**Comment by lanzafame** [comment]
It isn't because I failed to search PRs when checking whether this was done, and only searched issues. 🤦

**Review by aschmahmann — APPROVED** [review]

**Comment by aschmahmann** [comment]
Oops, sorry @lanzafame clicked the wrong PR by accident. We're merging #181

**Comment by lanzafame** [comment]
@aschmahmann no worries, just happy to see this has finally happened

**Pull request closed without merging**
