### PR TITLE
fix leveldb iterator

### PR DESCRIPTION
**Pull request by ebuchman**

### CODE REVIEW

**Comment by jbenet** [comment]
for reference: https://botbot.me/freenode/ipfs/2014-11-03/?msg=24723351&page=2

@ebuchman discovered that we've been using `i.Valid()` wrong and should really only use `i.Next()`.

**Comment by jbenet** [comment]
@ebuchman though, are we sure this is the case with the vendored version in this repo? 

Also, we may just want to update to latest leveldb. @maybebtc do you remember what the issue was on that?

**Comment by ebuchman** [comment]
I discovered the issue and originally fixed it deep within the bowels of the Godeps folder in `go-ipfs`. But I admit to zero competence in using Godeps.

**Comment by btc** [comment]
> Also, we may just want to update to latest leveldb. @maybebtc do you remember what the issue was on that?

a) A new version of  syndtr/goleveldb or b) the larger discussion about finding the best key value store based on ipfs' access patterns?

**Comment by jbenet** [comment]
>  a) A new version of syndtr/goleveldb

**Comment by btc** [comment]
I don't remember any fuss.

Though coverage is not comprehensive, go-datastore builds and tests pass.

https://github.com/maybebtc/datastore.go/compare/jbenet:master...maybebtc:deps?expand=1

**Pull request merged**
