### PR TITLE
Update .travis to run only on 1.7 and tip

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by Kubuxu** [comment]
Commit isn't signed by me as I created it from github ui.

**Comment by Kubuxu** [comment]
cc @whyrusleeping

**Comment by whyrusleeping** [comment]
@Kubuxu there isnt a go 1.7.3, use 1.7.1

**Comment by Kubuxu** [comment]
There is go 1.7.3 https://golang.org/dl/

**Comment by whyrusleeping** [comment]
huh, TIL. alright, LGTM

**Pull request merged**
