### PR TITLE
Fix channel buffer size in namespace datastore to use KeysOnlyBufSize

### PR DESCRIPTION
**Pull request by kevina**

### CODE REVIEW

**Comment by kevina** [comment]
See ipfs/go-ipfs#3376.

I better way would be to use something like `make(chan dsq.Result, cap(qr.Next()))` but for some reason that cap(qr.Next()) is returning 0 when it should be returning 128 (i.e. dsq.KeysOnlyBufSize) so I manually set the buffer size based on it it was a keys-only query.

**Comment by kevina** [comment]
Note the test failure is due to the use of go 1.6.3 that no longer appears to be supported with the latest version of go-datastore.

**Comment by Kubuxu** [comment]
Can you update the travis file to use 1.7.3 and tip.

**Comment by kevina** [comment]
@Kubuxu 

> Can you update the travis file to use 1.7.3 and tip.

Done.

**Comment by whyrusleeping** [comment]
Sweet, LGTM. I think the biggest problem here is that we're trying to use a channel as an iterator and thats just inherently slow. We can look at switching up interfaces later, but the changes being made so far look very promising

**Pull request merged**
