### PR TITLE
Import ds-help methods from go-ipfs/thirdparty

### PR DESCRIPTION
**Pull request by hsanjuan**
There is a TODO: put this code into the go-datastore itself.

I will PR to ipfs after this is merged and a new gx published.

### CODE REVIEW

**Review by magik6k — COMMENTED** [review]
go-datastore is not specific to IPFS, I'm not sure if we want these methods here.

**Comment by hsanjuan** [comment]
I can extract it to a separate repo. @whyrusleeping, you left that TODO. What do you think?

**Comment by whyrusleeping** [comment]
@hsanjuan Yeah, the weirdness is putting cids into go-datastore. I don't think they belong there.

**Comment by hsanjuan** [comment]
I will extract this to its own repo no problem :)

**Pull request closed without merging**
